<?php

namespace Database\Seeders;

use App\Models\Institution;
use Illuminate\Database\Seeder;

class AllInstitutionsSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['nku' => 'زانکۆی سەڵاحەدین - هەولێر', 'nen' => 'Salahaddin University - Erbil', 'nar' => 'جامعة صلاح الدين - أربيل', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://su.edu.krd', 'phone' => '066 223 0066', 'desc' => 'یەکەم زانکۆی هەرێمی کوردستان، دامەزراوە لە ساڵی ١٩٦٨.', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی زانست\\nکۆلێژی پزیشکی\\nکۆلێژی ئاداب\\nکۆلێژی یاسا\\nکۆلێژی کارگێڕی و ئابووری\\nکۆلێژی پەروەردە\\nکۆلێژی کشتوکاڵ\\nکۆلێژی سیاسی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئەندازیاری مەدەنی\\nبەشی ئەندازیاری کارەبا\\nبەشی کارگێڕی کار\\nبەشی ژمێریاری\\nبەشی یاسا\\nبەشی زمانی ئینگلیزی\\nبەشی زمانی کوردی\\nبەشی مێژوو\\nبەشی کیمیا\\nبەشی فیزیا\\nبەشی بایۆلۆجی', 'approved' => true],
            ['nku' => 'زانکۆی سلێمانی', 'nen' => 'University of Sulaimani', 'nar' => 'جامعة السليمانية', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'سلێمانی', 'web' => 'https://univsul.edu.iq', 'phone' => '053 312 1370', 'desc' => 'دامەزراوە لە ساڵی ١٩٦٨، یەکێکە لە زانکۆ گەورەکانی عێراق.', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی دەنتستری\\nکۆلێژی زانست\\nکۆلێژی کشتوکاڵ\\nکۆلێژی ئابووری\\nکۆلێژی یاسا و سیاسی', 'depts' => 'بەشی پزیشکی\\nبەشی دەنتستری\\nبەشی دەرمانسازی\\nبەشی کۆمپیوتەر\\nبەشی ئابووری\\nبەشی یاسا\\nبەشی زمانی کوردی', 'approved' => true],
            ['nku' => 'زانکۆی دهۆک', 'nen' => 'University of Duhok', 'nar' => 'جامعة دهوك', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'دهۆک', 'web' => 'https://uod.ac', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی دەنتستری\\nکۆلێژی زانست\\nکۆلێژی یاسا\\nکۆلێژی پەروەردەی بنەڕەتی\\nکۆلێژی کارگێڕی و ئابووری', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری مەدەنی\\nبەشی یاسا\\nبەشی کۆمپیوتەر\\nبەشی ئینگلیزی', 'approved' => true],
            ['nku' => 'زانکۆی پزیشکی هەولێر', 'nen' => 'Hawler Medical University', 'nar' => 'جامعة هولير الطبية', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://hmu.edu.krd', 'desc' => 'تەنها زانکۆی پزیشکی تایبەتمەندکراو لە هەرێمی کوردستان.', 'colleges' => 'کۆلێژی پزیشکی\\nکۆلێژی دەنتستری\\nکۆلێژی دەرمانسازی\\nکۆلێژی نەرسنگ', 'depts' => 'بەشی پزیشکی گشتی\\nبەشی دەنتستری\\nبەشی دەرمانسازی\\nبەشی تامارشناسی\\nبەشی نەرسنگ', 'approved' => true],
            ['nku' => 'زانکۆی کۆیە', 'nen' => 'Koya University', 'nar' => 'جامعة كويه', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'کۆیە', 'web' => 'https://koyauniversity.org', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی زانست و تەکنەلۆژیا\\nکۆلێژی کارگێڕی و ئابووری\\nکۆلێژی پەروەردە\\nکۆلێژی یاسا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئەندازیاری کارەبا\\nبەشی ئابووری\\nبەشی ئینگلیزی\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی سۆران', 'nen' => 'Soran University', 'nar' => 'جامعة سوران', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'سۆران', 'web' => 'https://soran.edu.iq', 'colleges' => 'کۆلێژی زانست\\nکۆلێژی ئەندازیاری\\nکۆلێژی پەروەردە\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ریاضی\\nبەشی کیمیا\\nبەشی کارگێڕی کار\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی زاخۆ', 'nen' => 'University of Zakho', 'nar' => 'جامعة زاخو', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'زاخۆ', 'web' => 'https://uoz.edu.krd', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی زانست\\nکۆلێژی پەروەردە\\nکۆلێژی یاسا\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئینگلیزی\\nبەشی یاسا\\nبەشی کارگێڕی کار', 'approved' => true],
            ['nku' => 'زانکۆی ڕاپەڕین', 'nen' => 'University of Raparin', 'nar' => 'جامعة رابرين', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'ڕاپەڕین', 'colleges' => 'کۆلێژی پەروەردە\\nکۆلێژی زانست\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی ئینگلیزی\\nبەشی ریاضی\\nبەشی ژمێریاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی هەڵەبجە', 'nen' => 'Halabja University', 'nar' => 'جامعة حلبجة', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'هەڵەبجە', 'colleges' => 'کۆلێژی پەروەردە\\nکۆلێژی زانست\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی ئینگلیزی\\nبەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی گەرمیان', 'nen' => 'Garmian University', 'nar' => 'جامعة گرميان', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'گەرمیان', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پەروەردە\\nکۆلێژی زانست\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئینگلیزی\\nبەشی ژمێریاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی چەرموو', 'nen' => 'Charmo University', 'nar' => 'جامعة جرمو', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'چەمچەماڵ', 'colleges' => 'کۆلێژی زانست\\nکۆلێژی کارگێڕی\\nکۆلێژی تەکنەلۆژیا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی ئابووری', 'approved' => true],
            ['nku' => 'زانکۆی پۆلیتەکنیکی هەولێر', 'nen' => 'Erbil Polytechnic University', 'nar' => 'جامعة أربيل التقنية', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://epu.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری تەکنیکی\\nکۆلێژی کارگێڕی تەکنیکی\\nکۆلێژی تەکنەلۆژیا\\nکۆلێژی تەندروستی', 'depts' => 'بەشی ئەندازیاری مەدەنی تەکنیکی\\nبەشی کۆمپیوتەر تەکنیکی\\nبەشی بیناسازی\\nبەشی ژمێریاری', 'approved' => true],
            ['nku' => 'زانکۆی پۆلیتەکنیکی سلێمانی', 'nen' => 'Sulaimani Polytechnic University', 'nar' => 'جامعة السليمانية التقنية', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'سلێمانی', 'web' => 'https://spu.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری تەکنیکی\\nکۆلێژی کشتوکاڵ تەکنیکی\\nکۆلێژی تەکنەلۆژیا', 'depts' => 'بەشی ئەندازیاری کارەبا\\nبەشی کۆمپیوتەر\\nبەشی کشتوکاڵ\\nبەشی ئابووری', 'approved' => true],
            ['nku' => 'زانکۆی پۆلیتەکنیکی دهۆک', 'nen' => 'Duhok Polytechnic University', 'nar' => 'جامعة دهوك التقنية', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'دهۆک', 'colleges' => 'کۆلێژی ئەندازیاری تەکنیکی\\nکۆلێژی کارگێڕی تەکنیکی\\nکۆلێژی تەکنەلۆژیا', 'depts' => 'بەشی ئەندازیاری مەدەنی\\nبەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی بیناسازی', 'approved' => true],
            ['nku' => 'زانکۆی کوردستان هەولێر', 'nen' => 'University of Kurdistan Hawler', 'nar' => 'جامعة كوردستان هولير', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://ukh.edu.krd', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی زانستی کۆمپیوتەر\\nکۆلێژی ژینگەی سروشتی\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی ئەندازیاری نەوت\\nبەشی کۆمپیوتەر\\nبەشی ژینگەناسی\\nبەشی کارگێڕی کار', 'approved' => true],
            ['nku' => 'زانکۆی ئەمریکی کوردستان', 'nen' => 'American University of Kurdistan', 'nar' => 'الجامعة الأمريكية في كردستان', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'دهۆک', 'web' => 'https://auk.edu.krd', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی بازرگانی\\nکۆلێژی هونەرو زانست', 'depts' => 'بەشی ئەندازیاری مەدەنی\\nبەشی کارگێڕی کار\\nبەشی ئینگلیزی\\nبەشی نەرسنگ', 'approved' => true],
            ['nku' => 'دامەزراوەی کوردستان بۆ خوێندنی ستراتیژی', 'nen' => 'Kurdistan Institution for Strategic Studies', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'دیوانی پزیشکی تایبەت کوردستان', 'nen' => 'Kurdistan Board for Medical Specialties', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'زانکۆی ئەکرێ بۆ زانستە کاربەستییەکان', 'nen' => 'Akre University for Applied Sciences', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'ئاکرێ', 'colleges' => 'کۆلێژی زانست\\nکۆلێژی کارگێڕی\\nکۆلێژی پەروەردە', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی ئینگلیزی', 'approved' => true],
            ['nku' => 'زانکۆی پۆلیتەکنیکی گەرمیان', 'nen' => 'Garmian Polytechnic University', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'گەرمیان', 'colleges' => 'کۆلێژی ئەندازیاری تەکنیکی\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی ئەندازیاری مەدەنی\\nبەشی کۆمپیوتەر\\nبەشی ژمێریاری', 'approved' => true],
            ['nku' => 'زانکۆی ئەمریکی عێراق - سلێمانی', 'nen' => 'American University of Iraq - Sulaimani', 'nar' => 'الجامعة الأمريكية في العراق - السليمانية', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'web' => 'https://auis.edu.krd', 'desc' => 'زانکۆیەکی تایبەت و نێودەوڵەتییە بە ستاندارەکانی ئەمریکا.', 'colleges' => 'کۆلێژی بازرگانی\\nکۆلێژی هونەرو زانست\\nکۆلێژی ئەندازیاری', 'depts' => 'بەشی کارگێڕی کار\\nبەشی ئابووری\\nبەشی ئینگلیزی\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی گەشەپێدانی مرۆڤ', 'nen' => 'University of Human Development', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'colleges' => 'کۆلێژی زانست و تەکنەلۆژیا\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا\\nکۆلێژی پەروەردە', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی یاسا\\nبەشی ئینگلیزی', 'approved' => true],
            ['nku' => 'زانکۆی نەورۆز', 'nen' => 'Nawroz University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'دهۆک', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا\\nکۆلێژی پەروەردە', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی یاسا\\nبەشی ئینگلیزی', 'approved' => true],
            ['nku' => 'زانکۆی نۆلج', 'nen' => 'Knowledge University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا\\nکۆلێژی دەنتستری', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئەندازیاری مەدەنی\\nبەشی ژمێریاری\\nبەشی دەنتستری', 'approved' => true],
            ['nku' => 'زانکۆی لوبنانی-فەرەنسی', 'nen' => 'Lebanese French University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://lfu.edu.krd', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی بازرگانی\\nکۆلێژی زانست\\nکۆلێژی یاسا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی کارگێڕی کار\\nبەشی ئینگلیزی\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی جیهان - هەولێر', 'nen' => 'Cihan University - Erbil', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://cihanuniversity.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا\\nکۆلێژی پزیشکی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی یاسا\\nبەشی دەنتستری', 'approved' => true],
            ['nku' => 'زانکۆی جیهان - سلێمانی', 'nen' => 'Cihan University - Sulaimani', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری', 'approved' => true],
            ['nku' => 'زانکۆی جیهان - دهۆک', 'nen' => 'Cihan University - Duhok', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'دهۆک', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری', 'approved' => true],
            ['nku' => 'زانکۆی نێودەوڵەتی هەولێر', 'nen' => 'International University of Erbil', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی کارگێڕی کار\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی کۆمار بۆ زانست و تەکنەلۆژیا', 'nen' => 'Komar University of Science and Technology', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی تەکنەلۆژیا\\nکۆلێژی پزیشکی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئەندازیاری کارەبا\\nبەشی پزیشکی', 'approved' => true],
            ['nku' => 'زانکۆی بایان', 'nen' => 'Bayan University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ژمێریاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی تیشک نێودەوڵەتی', 'nen' => 'Tishk International University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://tiu.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی کارگێڕی\\nکۆلێژی دەنتستری\\nکۆلێژی پزیشکی', 'depts' => 'بەشی کۆمپیوتەر\\nبەشی ئەندازیاری مەدەنی\\nبەشی دەنتستری\\nبەشی پزیشکی', 'approved' => true],
            ['nku' => 'زانکۆی تیشک - سلێمانی', 'nen' => 'Tishk University - Sulaimani', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'colleges' => 'کۆلێژی کارگێڕی\\nکۆلێژی یاسا', 'depts' => 'بەشی کارگێڕی کار\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی کاسۆلیک', 'nen' => 'Catholic University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'colleges' => 'کۆلێژی هونەرو زانست\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی ئینگلیزی\\nبەشی کارگێڕی کار', 'approved' => true],
            ['nku' => 'کۆلێژی قەڵا', 'nen' => 'Qala University College', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆلێژی گۆیژە', 'nen' => 'University College of Goizha', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'زانکۆی قەیوان نێودەوڵەتی', 'nen' => 'Qaiwan International University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'زانکۆی بریتانی نێودەوڵەتی', 'nen' => 'British International University', 'type' => 'priv', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'زانکۆی بەغدا', 'nen' => 'University of Baghdad', 'nar' => 'جامعة بغداد', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'بەغدا', 'web' => 'https://uobaghdad.edu.iq', 'desc' => 'گەورەترین و کۆنترین زانکۆی عێراق، دامەزراوە لە ١٩٥٧.', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی یاسا\\nکۆلێژی زانست\\nکۆلێژی ئاداب\\nکۆلێژی پەروەردە', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری مەدەنی\\nبەشی کۆمپیوتەر\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی مووسڵ', 'nen' => 'University of Mosul', 'nar' => 'جامعة الموصل', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'مووسڵ', 'web' => 'https://uomosul.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست\\nکۆلێژی یاسا', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی بەسرە', 'nen' => 'University of Basrah', 'nar' => 'جامعة البصرة', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'بەسرە', 'web' => 'https://uobasrah.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست\\nکۆلێژی ئاداب', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی کەرکووک', 'nen' => 'University of Kirkuk', 'nar' => 'جامعة كركوك', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'کەرکووک', 'web' => 'https://uokirkuk.edu.iq', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی یاسا\\nکۆلێژی کارگێڕی', 'depts' => 'بەشی پزیشکی\\nبەشی کۆمپیوتەر\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی تەکنەلۆژی - بەغدا', 'nen' => 'University of Technology - Baghdad', 'nar' => 'الجامعة التكنولوجية - بغداد', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'بەغدا', 'web' => 'https://uotechnology.edu.iq', 'desc' => 'زانکۆیەکی تایبەتمەندکراوی ئەندازیاری و تەکنەلۆژیا.', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی زانست', 'depts' => 'بەشی ئەندازیاری کارەبا\\nبەشی کۆمپیوتەر\\nبەشی مەکانیک\\nبەشی ئەندازیاری کیمیایی', 'approved' => true],
            ['nku' => 'زانکۆی نەهرەین', 'nen' => 'Al-Nahrain University', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'بەغدا', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی کووفە', 'nen' => 'University of Kufa', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'نەجەف', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی یاسا', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی کەربەلا', 'nen' => 'University of Kerbala', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'کەربەلا', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی یاسا', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی تکریت', 'nen' => 'Tikrit University', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'تکریت', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی ئەنبار', 'nen' => 'University of Anbar', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'ڕەمادی', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی بابل', 'nen' => 'University of Babylon', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'حیڵە', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی یاسا', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی ذی قار', 'nen' => 'University of Thi-Qar', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'ناسریە', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی واسط', 'nen' => 'Wasit University', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'کووت', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری', 'approved' => true],
            ['nku' => 'زانکۆی میسان', 'nen' => 'University of Misan', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'عەمارە', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری', 'approved' => true],
            ['nku' => 'زانکۆی مستەنسریە', 'nen' => 'Al-Mustansiriya University', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'بەغدا', 'desc' => 'یەکێکە لە کۆنترین زانکۆکانی جیهان، بەناو لە ساڵی ١٢٣٣.', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی یاسا\\nکۆلێژی پەروەردە', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی یاسا', 'approved' => true],
            ['nku' => 'زانکۆی دیالە', 'nen' => 'University of Diyala', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'بەعقووبە', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی\\nکۆلێژی زانست', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری\\nبەشی کۆمپیوتەر', 'approved' => true],
            ['nku' => 'زانکۆی قادسیە', 'nen' => 'University of Al-Qadisiyah', 'type' => 'gov', 'country' => 'عێراق', 'city' => 'دیوانیە', 'colleges' => 'کۆلێژی ئەندازیاری\\nکۆلێژی پزیشکی', 'depts' => 'بەشی پزیشکی\\nبەشی ئەندازیاری', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی ئارارات', 'nen' => 'Ararat Private Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی ئایندا', 'nen' => 'Ayinda Private Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی دهۆک', 'nen' => 'Duhok Private Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی گەشە', 'nen' => 'Gasha Private Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی هەیبەت سولتان', 'nen' => 'Haibat Sultan Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی کەلار', 'nen' => 'Kalar Private Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'کەلار', 'approved' => true],
            ['nku' => 'دامەزراوەی نیشتمانی کوردستان بۆ تەکنەلۆژیا', 'nen' => 'Kurdistan National Institute of Technology', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی کوردستان - سلێمانی', 'nen' => 'Kurdistan Technical Institute - Sulaimani', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی نۆبڵ', 'nen' => 'Noble Private Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی پایتەخت - هەولێر', 'nen' => 'Paitaxt Technical Institute - Erbil', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'web' => 'https://pti.edu.krd', 'logo' => 'https://pti.edu.krd/wp-content/uploads/2021/03/PAITAXT-c-scaled.jpg', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی ڕەواندوز', 'nen' => 'Rawanduz Private Technical Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'ڕەواندوز', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی ڕەواندوز - لقی زاخۆ', 'nen' => 'Rawanduz Technical Institute - Zakho Branch', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'زاخۆ', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی پریم', 'nen' => 'Prime Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی سەفین - شەقڵاوە', 'nen' => 'Safin Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'شەقڵاوە', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی پیرمام', 'nen' => 'Pirmam Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی یونیڤەرساڵ', 'nen' => 'Universal Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی و پیشەیی بێست', 'nen' => 'Best Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی نۆلج', 'nen' => 'Knowledge Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی CMC', 'nen' => 'CMC Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'دامەزراوەی نیشتمانی تەکنیکی', 'nen' => 'National Technical Institute for Technology', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی ئازمەر', 'nen' => 'Azmar Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی برایت', 'nen' => 'Bright Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی گەرمیان', 'nen' => 'Garmyan Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'گەرمیان', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی ڕاپەڕین', 'nen' => 'Raparin Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'ڕاپەڕین', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی لووتکە', 'nen' => 'Lutka Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی هەڵەبجە', 'nen' => 'Halabja Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەڵەبجە', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی کۆمار', 'nen' => 'Komar Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی فام', 'nen' => 'Fam Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی جیهان - سلێمانی', 'nen' => 'Cihan Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی چارستین', 'nen' => 'Charstin Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی برایت ماینز', 'nen' => 'Bright Minds Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی بەهدینان', 'nen' => 'Behdinan Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی سیپا', 'nen' => 'Sipa Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی و پیشەیی پایتەختی کوردستان', 'nen' => 'Kurdistan Capital Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی تەکنیکی رۆژ', 'nen' => 'Roj Technical and Vocational Institute', 'type' => 'inst2', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی (کۆشش) بنەرەتی ناحکومی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانا ستیراطەش / زمانی ئینگلیزی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'ئاکرێ', 'approved' => true],
            ['nku' => 'قوتابخانەی ئیشق دهۆک ماسیکێ', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'کۆلیژا ئیشق دهۆک', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'باخچەی ساوایانی لارا / ئەندازیاران', 'type' => 'kg', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'باخچەی باڵای ناحکومی', 'type' => 'kg', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'باخچەی ساوایانی خانزاد', 'type' => 'kg', 'country' => 'عێراق', 'city' => 'کۆیە', 'approved' => true],
            ['nku' => 'باخچەی ساوایانی سات', 'type' => 'kg', 'country' => 'عێراق', 'city' => 'کۆیە', 'approved' => true],
            ['nku' => 'ئامادەیی زانیاری ئەهلی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی ساڤا بنەرەتی / ئامادەیی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی نوری بنەرەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی سمارتی بنەرەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆمەڵگەی باڵای ئامادەیی / ١', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'باخچەی ساوایانی هێنەر', 'type' => 'kg', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی میدیای نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی کامبریدجی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی شادی ئەهلی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی کەرکوک بۆ زانستی کۆمپیوتەر', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'کەرکووک', 'approved' => true],
            ['nku' => 'پەیمانگەی زانست', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی گارە بۆ زانستی کۆمپیوتەر', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'پەیمانگەی سلێمانی', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'پەیمانگەی لاڤین', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پەیمانگەی قەڵا و منارە بۆ زانستی کۆمپیوتەر', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کەلاری نێودەوڵەتی – سابیس', 'type' => 'school', 'country' => 'عێراق', 'city' => 'کەلار', 'approved' => true],
            ['nku' => 'پەیمانگەی ھەولێر بۆ زانستی کۆمپیوتەر', 'type' => 'inst5', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'زاخۆی نێودەوڵەتی – سابیس', 'type' => 'school', 'country' => 'عێراق', 'city' => 'زاخۆ', 'approved' => true],
            ['nku' => 'سلێمانی نێودەوڵەتی – سابیس', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئامادەیی ئاسۆی میللی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'سەردەمی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'بەریتانی ھەولێری بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی نیرۆژ', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'دیدەمی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی سۆرانی نوێ', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سۆران', 'approved' => true],
            ['nku' => 'میدیای ھەولێری نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی زانای ئەهلی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی لاژە', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'نوری بنەڕەتی / کوردی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'نوری بنەڕەتی / عەرەبی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی ڕەوای ئێواران', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی کلێڤەری بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئەمەریکی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی ژیاری ئەهلی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'دانیال میترانی سلێمانی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'کامبریدجی سلێمانی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئامادەیی ژیاری ئێوارانی ئەهلی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'بڕیاری بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'سۆرانی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سۆران', 'approved' => true],
            ['nku' => 'بەریتانی سلێمانی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئامادەیی لاژەی ئێواران', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کوین ئانی بنەڕەتی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'دانیال میترانی نێودەوڵەتی فەرەنسی - هەولێر', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'پای بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'کۆلێجی ئیشقی سۆران', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سۆران', 'approved' => true],
            ['nku' => 'شویفاتی سلێمانی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'شیاوی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆمەڵگەی لانە / هەڤاڵان', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'سەروەرانی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی ئەنالیندی پیرمام', 'type' => 'school', 'country' => 'عێراق', 'city' => 'پیرمام', 'approved' => true],
            ['nku' => 'کۆمەڵگەی باڵا /٢', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ژیاری بنەڕەتی /١', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'نۆلجی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'فلۆرەنتینی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'برادۆستی ڕانیەی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'ڕانیە', 'approved' => true],
            ['nku' => 'ژیاری بنەڕەتی /٢', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی شەهید فاخیر مێرگەسۆر', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆلێژی ھەڵەبجەی شەھید', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەڵەبجە', 'approved' => true],
            ['nku' => 'کۆمەڵگەی باڵای بنەرەتی / ١', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆلێژی سلێمانی کچان', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'کۆلێژی سەلاحەددینی کوڕان', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئەڵمانی نێودەوڵەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کامبریدجی نێودەوڵەتی - شاری ئالتون', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'لارای بنەڕەتی / موفتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'نیلۆڤەری بنەڕەتی کچان', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'سلێمانی بنەڕەتی /٢', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئیشقی / ڕۆناکی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی فاخیر مێرگەسۆر', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆمەڵگەی فێنک', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی ڕۆنا بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'قوتابخانەی ئاگا - پیرمام', 'type' => 'school', 'country' => 'عێراق', 'city' => 'پیرمام', 'approved' => true],
            ['nku' => 'کۆلێجی جیھان بنەرەتی / ئامادەیی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'جونێری بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئیشقی برایەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'کۆمەڵگەها دهۆک نێودەوڵەتی ئینگلیزی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'لیزای بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'باخچە و قوتابخانا میدیا دھۆک', 'type' => 'kg', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'میدیای نێودەوڵەتی سلێمانی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ھیزلی نموونەیی ئینگلیزی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'سلێمانی بنەڕەتی /١', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'ئاشتی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'سلێمانی', 'approved' => true],
            ['nku' => 'کۆلێجی ئیشقی دھۆک', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'ئیشقی ماسیکی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'دهۆک', 'approved' => true],
            ['nku' => 'ئیشقی بنەڕەتی کوڕان', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئیحسان دۆغرامەچی - بلکەنت', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'شویفاتی نێودەوڵەتی هەولێر', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی نیلۆڤەری نمونەیی کچان', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئیشق / گوڵانی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئیشق / رۆناکی بنەڕەتی', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
            ['nku' => 'ئامادەیی ئیشقی کوڕان / وەزیران', 'type' => 'school', 'country' => 'عێراق', 'city' => 'هەولێر', 'approved' => true],
        ];

        foreach ($data as $item) {
            if (empty($item['type'])) continue;
            Institution::updateOrCreate(
                ['nku' => $item['nku'], 'type' => $item['type']],
                $item
            );
        }
    }
}
