<?php

namespace Database\Seeders;

use App\Models\Institution;
use Illuminate\Database\Seeder;

class FiftyInstitutionSeeder extends Seeder
{
    public function run(): void
    {
        $institutions = [
            // ─── زانکۆ حکومی (gov) ───
            [
                'nku' => 'زانکۆی پۆلیتەکنیکی هەولێر',
                'nen' => 'Erbil Polytechnic University',
                'nar' => 'جامعة أربيل التقنية',
                'type' => 'gov',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'web' => 'https://epu.edu.iq/',
                'phone' => '07504123456',
                'email' => 'info@epu.edu.iq',
                'addr' => 'شەقامی ١٠٠ مەتری، هەولێر',
                'desc' => 'زانکۆی پۆلیتەکنیکی هەولێر لە ساڵی ٢٠١٢ دامەزراوە و لە بوارەکانی ئەندازیاری، تەکنەلۆژیا، و بەڕێوەبردنی کار کار دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی ئەندازیاری', 'departments' => []],
                    ['name' => 'کۆلێژی تەکنەلۆژیای زانیاری', 'departments' => []],
                    ['name' => 'کۆلێژی بەڕێوەبردن', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی پۆلیتەکنیکی سلێمانی',
                'nen' => 'Sulaimani Polytechnic University',
                'nar' => 'جامعة السليمانية التقنية',
                'type' => 'gov',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'web' => 'https://spu.edu.iq/',
                'phone' => '07701234567',
                'email' => 'info@spu.edu.iq',
                'addr' => 'گەڕەکی قەڵاچوالان، سلێمانی',
                'desc' => 'زانکۆی پۆلیتەکنیکی سلێمانی لە بوارەکانی تەکنیکی و پیشەیی خزمەت دەکات و کۆلێژ و پەیمانگای زۆری هەیە.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی ئەندازیاری تەکنیکی', 'departments' => []],
                    ['name' => 'کۆلێژی تەندروستی', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی هەڵەبجە',
                'nen' => 'University of Halabja',
                'nar' => 'جامعة حلبجة',
                'type' => 'gov',
                'country' => 'عێراق',
                'city' => 'هەڵەبجە',
                'web' => 'https://uoh.edu.iq/',
                'phone' => '07701112233',
                'email' => 'info@uoh.edu.iq',
                'addr' => 'شاری هەڵەبجە',
                'desc' => 'زانکۆی هەڵەبجە لە ساڵی ٢٠١١ دامەزراوە و لە بوارەکانی زانست و ئەدەب خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی زانست', 'departments' => []],
                    ['name' => 'کۆلێژی ئەدەب', 'departments' => []],
                    ['name' => 'کۆلێژی پەروەردە', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی زاخۆ',
                'nen' => 'University of Zakho',
                'nar' => 'جامعة زاخو',
                'type' => 'gov',
                'country' => 'عێراق',
                'city' => 'زاخۆ',
                'web' => 'https://uoz.edu.krd/',
                'phone' => '07504445566',
                'email' => 'info@uoz.edu.krd',
                'addr' => 'شاری زاخۆ، دهۆک',
                'desc' => 'زانکۆی زاخۆ لە ساڵی ٢٠١٠ وەک زانکۆیەکی سەربەخۆ دامەزرا و چەندین کۆلێژی هەیە.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی زانست', 'departments' => []],
                    ['name' => 'کۆلێژی ئەدەبیات', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی چەرمۆ',
                'nen' => 'Charmo University',
                'nar' => 'جامعة جرمو',
                'type' => 'gov',
                'country' => 'عێراق',
                'city' => 'چەمچەماڵ',
                'web' => 'https://charmouniversity.org/',
                'phone' => '07701234568',
                'email' => 'info@charmouniversity.org',
                'addr' => 'شاری چەمچەماڵ',
                'desc' => 'زانکۆی چەرمۆ لە ساڵی ٢٠١٤ لە شاری چەمچەماڵ دامەزرا.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی زانست و تەکنەلۆژیا', 'departments' => []],
                    ['name' => 'کۆلێژی پەروەردە', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی سۆران',
                'nen' => 'Soran University',
                'nar' => 'جامعة سوران',
                'type' => 'gov',
                'country' => 'عێراق',
                'city' => 'سۆران',
                'web' => 'https://soran.edu.iq/',
                'phone' => '07504567890',
                'email' => 'info@soran.edu.iq',
                'addr' => 'شاری سۆران، هەولێر',
                'desc' => 'زانکۆی سۆران لە ساڵی ٢٠٠٩ دامەزرا و لە بوارەکانی زانست و ئەندازیاری خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی زانست', 'departments' => []],
                    ['name' => 'کۆلێژی ئەندازیاری', 'departments' => []],
                    ['name' => 'کۆلێژی ئەدەب', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],

            // ─── زانکۆ تایبەت (priv) ───
            [
                'nku' => 'زانکۆی ئەمەریکی - کوردستان',
                'nen' => 'American University of Kurdistan',
                'nar' => 'الجامعة الأمريكية في كردستان',
                'type' => 'priv',
                'country' => 'عێراق',
                'city' => 'دهۆک',
                'web' => 'https://auk.edu.krd/',
                'phone' => '07504001122',
                'email' => 'info@auk.edu.krd',
                'addr' => 'شاری دهۆک',
                'desc' => 'زانکۆی ئەمەریکی لە کوردستان لە ساڵی ٢٠١٤ دامەزرا و بە سیستەمی ئەمەریکی خوێندن دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی کارگێڕی کار', 'departments' => []],
                    ['name' => 'کۆلێژی ئەندازیاری', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی نۆلج',
                'nen' => 'Knowledge University',
                'nar' => 'جامعة نولج',
                'type' => 'priv',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'web' => 'https://knu.edu.iq/',
                'phone' => '07505556677',
                'email' => 'info@knu.edu.iq',
                'addr' => 'شەقامی ١٢٠ مەتری، هەولێر',
                'desc' => 'زانکۆی نۆلج زانکۆیەکی تایبەتە لە هەولێر و لە بوارەکانی پزیشکی، ئەندازیاری و یاسا خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی پزیشکی', 'departments' => []],
                    ['name' => 'کۆلێژی یاسا', 'departments' => []],
                    ['name' => 'کۆلێژی ئەندازیاری', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی ئەهلیەی هەولێر',
                'nen' => 'Erbil Private University',
                'nar' => 'جامعة أربيل الأهلية',
                'type' => 'priv',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'web' => 'https://epu.edu.krd/',
                'phone' => '07506667788',
                'email' => 'info@epu-private.edu.krd',
                'addr' => 'گەڕەکی ئەنکاوا، هەولێر',
                'desc' => 'زانکۆی ئەهلیەی هەولێر لە بوارەکانی بەڕێوەبردن و کۆمپیوتەر خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی بەڕێوەبردنی کار', 'departments' => []],
                    ['name' => 'کۆلێژی کۆمپیوتەر', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی ئیشک',
                'nen' => 'Ishik University',
                'nar' => 'جامعة إشك',
                'type' => 'priv',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'web' => 'https://tiu.edu.iq/',
                'phone' => '07507778899',
                'email' => 'info@tiu.edu.iq',
                'addr' => 'ڕێگای ٦٠ مەتری، هەولێر',
                'desc' => 'زانکۆی ئیشک (ئێستا تشرین) لە ساڵی ٢٠٠٨ دامەزرا و بەشە جیاوازەکانی تێدایە.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی ئەندازیاری', 'departments' => []],
                    ['name' => 'کۆلێژی پەروەردە', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی سلێمانی تایبەت',
                'nen' => 'University of Sulaimani - Private',
                'nar' => 'جامعة السليمانية الخاصة',
                'type' => 'priv',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07701239876',
                'email' => 'info@usp.edu.krd',
                'desc' => 'زانکۆیەکی تایبەتە لە سلێمانی کە لە بوارەکانی زانست و تەکنەلۆژیا خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی زانست', 'departments' => []],
                    ['name' => 'کۆلێژی تەکنەلۆژیا', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],

            // ─── پەیمانگەی ٥ ساڵی (inst5) ───
            [
                'nku' => 'پەیمانگای تەکنیکی هەولێر',
                'nen' => 'Erbil Technical Institute',
                'nar' => 'المعهد التقني أربيل',
                'type' => 'inst5',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07508001122',
                'email' => 'info@eti.edu.iq',
                'desc' => 'پەیمانگای تەکنیکی هەولێر لە بوارەکانی تەکنیکی و پیشەیی خزمەت دەکات و بڕوانامای دبلۆم تەکنیکی دەبەخشێت.',
                'colleges' => json_encode([
                    ['name' => 'بەشی ئەندازیاری کۆمپیوتەر', 'departments' => []],
                    ['name' => 'بەشی کارەبا', 'departments' => []],
                    ['name' => 'بەشی میکانیک', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای تەکنیکی سلێمانی',
                'nen' => 'Sulaimani Technical Institute',
                'nar' => 'المعهد التقني السليمانية',
                'type' => 'inst5',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07708002233',
                'email' => 'info@sti.edu.iq',
                'desc' => 'پەیمانگای تەکنیکی سلێمانی یەکێکە لە پەیمانگا کۆنەکانی هەرێم و لە بوارەکانی جۆراوجۆر خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'بەشی ژمێریاری', 'departments' => []],
                    ['name' => 'بەشی تەندروستی', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای تەکنیکی کۆیە',
                'nen' => 'Koya Technical Institute',
                'type' => 'inst5',
                'country' => 'عێراق',
                'city' => 'کۆیە',
                'phone' => '07508003344',
                'desc' => 'پەیمانگای تەکنیکی کۆیە لە بوارەکانی تەکنیکی خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'بەشی کۆمپیوتەر', 'departments' => []],
                    ['name' => 'بەشی کارگێڕی', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای تەکنیکی ڕاپەرین',
                'nen' => 'Raparin Technical Institute',
                'type' => 'inst5',
                'country' => 'عێراق',
                'city' => 'ڕانیە',
                'phone' => '07708004455',
                'desc' => 'پەیمانگای تەکنیکی ڕاپەرین لە شاری ڕانیە.',
                'colleges' => json_encode([
                    ['name' => 'بەشی کارەبا', 'departments' => []],
                    ['name' => 'بەشی ژمێریاری', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],

            // ─── پەیمانگەی ٢ ساڵی (inst2) ───
            [
                'nku' => 'پەیمانگای رۆیاڵ',
                'nen' => 'Royal Institute',
                'type' => 'inst2',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07509001122',
                'email' => 'info@royalinstitute.com',
                'desc' => 'پەیمانگای رۆیاڵ پەیمانگایەکی تایبەتی ٢ ساڵییە لە هەولێر و بەشەکانی ژمێریاری و کۆمپیوتەری تێدایە.',
                'colleges' => json_encode([
                    ['name' => 'ژمێریاری', 'departments' => []],
                    ['name' => 'کۆمپیوتەر', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای ئەکادیمی',
                'nen' => 'Academy Institute',
                'type' => 'inst2',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07709002233',
                'email' => 'info@academy-inst.com',
                'desc' => 'پەیمانگای ئەکادیمی لە سلێمانی بەشەکانی زمانی ئینگلیزی و کارگێڕی کاری تێدایە.',
                'colleges' => json_encode([
                    ['name' => 'زمانی ئینگلیزی', 'departments' => []],
                    ['name' => 'کارگێڕی کار', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای نەورۆز',
                'nen' => 'Nawroz Private Institute',
                'type' => 'inst2',
                'country' => 'عێراق',
                'city' => 'دهۆک',
                'phone' => '07509003344',
                'desc' => 'پەیمانگای نەورۆز لە دهۆک بەشەکانی پەرستاری و دەرمانسازی و ژمێریاری هەیە.',
                'colleges' => json_encode([
                    ['name' => 'پەرستاری', 'departments' => []],
                    ['name' => 'دەرمانسازی', 'departments' => []],
                    ['name' => 'ژمێریاری', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای گەشەپێدان',
                'nen' => 'Development Institute',
                'type' => 'inst2',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07509004455',
                'desc' => 'پەیمانگای گەشەپێدان لە بوارەکانی کۆمپیوتەر و بەڕێوەبردن خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆمپیوتەر', 'departments' => []],
                    ['name' => 'بەڕێوەبردن', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای ئاشتی',
                'nen' => 'Ashti Institute',
                'type' => 'inst2',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07709005566',
                'desc' => 'پەیمانگای ئاشتی لە سلێمانی لە بوارەکانی تەندروستی و شیکاری تایبەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'پەرستاری', 'departments' => []],
                    ['name' => 'شیکاری نەخۆشیەکان', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],

            // ─── قوتابخانە (school) ───
            [
                'nku' => 'قوتابخانەی ئەفرەت',
                'nen' => 'Afrat School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07505551122',
                'desc' => 'قوتابخانەی ئەفرەت قوتابخانەیەکی تایبەتە لە هەولێر بۆ خوێندنی ئامادەیی و بنەڕەتی.',
                'approved' => true,
            ],
            [
                'nku' => 'قوتابخانەی بریار',
                'nen' => 'Bryar School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07705552233',
                'desc' => 'قوتابخانەی بریار قوتابخانەیەکی تایبەتی نێودەوڵەتییە لە سلێمانی.',
                'approved' => true,
            ],
            [
                'nku' => 'قوتابخانەی ئامانج',
                'nen' => 'Amanj School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07505553344',
                'desc' => 'قوتابخانەی ئامانج قوتابخانەیەکی نوێیە لە هەولێر بۆ قۆناغی بنەڕەتی و ناوەندی.',
                'approved' => true,
            ],
            [
                'nku' => 'قوتابخانەی هاوکار',
                'nen' => 'Hawkar School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'دهۆک',
                'phone' => '07505554455',
                'desc' => 'قوتابخانەی هاوکار لە دهۆک بۆ قۆناغی ئامادەیی.',
                'approved' => true,
            ],
            [
                'nku' => 'قوتابخانەی ڕۆشنا',
                'nen' => 'Roshna School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07705555566',
                'desc' => 'قوتابخانەی ڕۆشنا قوتابخانەیەکی تایبەتی کوالیتییە لە سلێمانی.',
                'approved' => true,
            ],
            [
                'nku' => 'قوتابخانەی نەخشین',
                'nen' => 'Nakhshin School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07505556677',
                'desc' => 'قوتابخانەی نەخشین بۆ قۆناغی بنەڕەتی و ناوەندی لە هەولێر.',
                'approved' => true,
            ],

            // ─── باخچەی منداڵان (kg) ───
            [
                'nku' => 'باخچەی ئاسمان',
                'nen' => 'Asman Kindergarten',
                'type' => 'kg',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07506661122',
                'desc' => 'باخچەی ئاسمان باخچەیەکی نوێیە بۆ تەمەنی ٣-٦ ساڵ لە هەولێر.',
                'approved' => true,
            ],
            [
                'nku' => 'باخچەی ڕۆژ',
                'nen' => 'Rozh Kindergarten',
                'type' => 'kg',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07706662233',
                'desc' => 'باخچەی ڕۆژ باخچەیەکی تایبەتە بۆ خوێندنی پێش‌دەبستانی لە سلێمانی.',
                'approved' => true,
            ],
            [
                'nku' => 'باخچەی ستێرە',
                'nen' => 'Stere Kindergarten',
                'type' => 'kg',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07506663344',
                'desc' => 'باخچەی ستێرە بۆ منداڵانی تەمەنی ٢.٥ تا ٦ ساڵ.',
                'approved' => true,
            ],
            [
                'nku' => 'باخچەی هەناسە',
                'nen' => 'Hanasa Kindergarten',
                'type' => 'kg',
                'country' => 'عێراق',
                'city' => 'دهۆک',
                'phone' => '07506664455',
                'desc' => 'باخچەی هەناسە لە دهۆک بۆ منداڵانی پێش‌دەبستانی.',
                'approved' => true,
            ],

            // ─── دایەنگە (dc) ───
            [
                'nku' => 'دایەنگەی سروشت',
                'nen' => 'Srusht Daycare',
                'type' => 'dc',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07507771122',
                'desc' => 'دایەنگەی سروشت بۆ منداڵانی تەمەنی ٦ مانگ تا ٣ ساڵ لە هەولێر.',
                'approved' => true,
            ],
            [
                'nku' => 'دایەنگەی ئەستێرە',
                'nen' => 'Estere Daycare',
                'type' => 'dc',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07707772233',
                'desc' => 'دایەنگەی ئەستێرە لە سلێمانی بۆ چاودێری منداڵان.',
                'approved' => true,
            ],
            [
                'nku' => 'دایەنگەی گوڵینە',
                'nen' => 'Guline Daycare',
                'type' => 'dc',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07507773344',
                'desc' => 'دایەنگەی گوڵینە بۆ چاودێری ڕۆژانەی منداڵان لە هەولێر.',
                'approved' => true,
            ],

            // ─── سەنتەری زمان/پیشەیی (lang) ───
            [
                'nku' => 'سەنتەری زمانی بریتیش',
                'nen' => 'British Language Center',
                'type' => 'lang',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07508881122',
                'email' => 'info@blc-erbil.com',
                'desc' => 'سەنتەری زمانی بریتیش بۆ فێرکردنی زمانی ئینگلیزی بە ئاستی نێودەوڵەتی.',
                'approved' => true,
            ],
            [
                'nku' => 'سەنتەری زمانی وال ستریت',
                'nen' => 'Wall Street English Center',
                'type' => 'lang',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07508882233',
                'desc' => 'سەنتەری وال ستریت بۆ فێرکردنی زمانی ئینگلیزی بە مەتۆدی نوێ.',
                'approved' => true,
            ],
            [
                'nku' => 'سەنتەری توانا بۆ زمانەکان',
                'nen' => 'Twana Language Center',
                'type' => 'lang',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07708883344',
                'desc' => 'سەنتەری توانا بۆ فێرکردنی زمانەکانی ئینگلیزی، تورکی، و ئەڵمانی.',
                'approved' => true,
            ],
            [
                'nku' => 'سەنتەری پیشەیی ئینۆڤەیشن',
                'nen' => 'Innovation Skills Center',
                'type' => 'lang',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07508884455',
                'desc' => 'سەنتەری پیشەیی ئینۆڤەیشن بۆ فێرکردنی تەکنەلۆژیا و پرۆگرامینگ.',
                'approved' => true,
            ],

            // ─── کۆمەڵکای پەروەردەیی (edu) ───
            [
                'nku' => 'کۆمپلێکسی خوێندنی ڕۆشنگەری',
                'nen' => 'Roshngarey Education Complex',
                'type' => 'edu',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07509991122',
                'desc' => 'کۆمپلێکسی خوێندنی ڕۆشنگەری کە قوتابخانە و باخچە و سەنتەری تێدایە.',
                'approved' => true,
            ],
            [
                'nku' => 'کۆمەڵکای پەروەردەیی داناگۆ',
                'nen' => 'Danago Education Complex',
                'type' => 'edu',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07709992233',
                'desc' => 'کۆمەڵکای داناگۆ کۆمەڵکایەکی تەواوی پەروەردەییە لە سلێمانی.',
                'approved' => true,
            ],
            [
                'nku' => 'کۆمەڵکای پەروەردەیی هیوا',
                'nen' => 'Hewa Education Complex',
                'type' => 'edu',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07509993344',
                'desc' => 'کۆمەڵکای پەروەردەیی هیوا لە هەولێر قوتابخانەی بنەڕەتی و ناوەندی و ئامادەیی هەیە.',
                'approved' => true,
            ],

            // ─── زانکۆی ئێواران (eve_uni) ───
            [
                'nku' => 'زانکۆی ئێوارانی هەولێر',
                'nen' => 'Erbil Evening University',
                'type' => 'eve_uni',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07501112233',
                'desc' => 'زانکۆی ئێوارانی هەولێر بۆ ئەو کەسانەی کە لە ڕۆژ کار دەکەن و لە ئێواران دەیانەوێ بخوێنن.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی یاسا', 'departments' => []],
                    ['name' => 'کۆلێژی بەڕێوەبردن', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'زانکۆی ئێوارانی سلێمانی',
                'nen' => 'Sulaimani Evening University',
                'type' => 'eve_uni',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07701113344',
                'desc' => 'زانکۆی ئێوارانی سلێمانی بۆ خوێندنی ئێواران.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی ئەدەب', 'departments' => []],
                    ['name' => 'کۆلێژی زانست', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],

            // ─── پەیمانگای ئێواران (eve_inst) ───
            [
                'nku' => 'پەیمانگای ئێوارانی هەولێر',
                'nen' => 'Erbil Evening Institute',
                'type' => 'eve_inst',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07501114455',
                'desc' => 'پەیمانگای ئێوارانی هەولێر بۆ خوێندنی ئێوارانی بەشەکانی کۆمپیوتەر و ژمێریاری.',
                'colleges' => json_encode([
                    ['name' => 'کۆمپیوتەر', 'departments' => []],
                    ['name' => 'ژمێریاری', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای ئێوارانی سلێمانی',
                'nen' => 'Sulaimani Evening Institute',
                'type' => 'eve_inst',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07701115566',
                'desc' => 'پەیمانگای ئێوارانی سلێمانی بۆ خوێندنی بەشەکانی کارگێڕی و زمان.',
                'colleges' => json_encode([
                    ['name' => 'کارگێڕی', 'departments' => []],
                    ['name' => 'زمانی ئینگلیزی', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],

            // ─── زیاتر زانکۆ و پەیمانگا ───
            [
                'nku' => 'زانکۆی نەورۆز',
                'nen' => 'Nawroz University',
                'nar' => 'جامعة نوروز',
                'type' => 'priv',
                'country' => 'عێراق',
                'city' => 'دهۆک',
                'web' => 'https://nawrozuniversity.com/',
                'phone' => '07504223344',
                'email' => 'info@nawroz.edu.krd',
                'desc' => 'زانکۆی نەورۆز زانکۆیەکی تایبەتە لە دهۆک و لە بوارەکانی ئەندازیاری و کارگێڕی خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'کۆلێژی ئەندازیاری', 'departments' => []],
                    ['name' => 'کۆلێژی کارگێڕی کار', 'departments' => []],
                    ['name' => 'کۆلێژی یاسا و سیاسە', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'پەیمانگای مێدیا',
                'nen' => 'Media Institute',
                'type' => 'inst2',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07509116677',
                'desc' => 'پەیمانگای مێدیا لە بوارەکانی ڕاگەیاندن و مێدیا خزمەت دەکات.',
                'colleges' => json_encode([
                    ['name' => 'ڕاگەیاندن', 'departments' => []],
                    ['name' => 'دیزاین', 'departments' => []],
                ], JSON_UNESCAPED_UNICODE),
                'approved' => true,
            ],
            [
                'nku' => 'قوتابخانەی ئاکاد',
                'nen' => 'Akad School',
                'type' => 'school',
                'country' => 'عێراق',
                'city' => 'هەولێر',
                'phone' => '07505557788',
                'desc' => 'قوتابخانەی ئاکاد قوتابخانەیەکی تایبەتی نێودەوڵەتییە لە هەولێر.',
                'approved' => true,
            ],
            [
                'nku' => 'سەنتەری ئایتی پلەس',
                'nen' => 'IT Plus Center',
                'type' => 'lang',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07708885566',
                'desc' => 'سەنتەری ئایتی پلەس بۆ فێرکردنی بوارەکانی ئایتی و پرۆگرامینگ.',
                'approved' => true,
            ],
            [
                'nku' => 'باخچەی تاڤ',
                'nen' => 'Tav Kindergarten',
                'type' => 'kg',
                'country' => 'عێراق',
                'city' => 'سلێمانی',
                'phone' => '07706665566',
                'desc' => 'باخچەی تاڤ بۆ منداڵانی تەمەنی ٣-٥ ساڵ لە سلێمانی.',
                'approved' => true,
            ],
        ];

        foreach ($institutions as $data) {
            Institution::updateOrCreate(
                [
                    'nen' => $data['nen'] ?? $data['nku'],
                    'city' => $data['city'] ?? null,
                ],
                $data
            );
        }
    }
}
